apiVersion: apps/v1
kind: Deployment
metadata:
  name: lithium
  labels:
    app: lithium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lithium
  template:
    metadata:
      labels:
        app: lithium
    spec:
      containers:
      - name: lithium
        image: lithium:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 500m
        envFrom:
        - configMapRef:
            name: lithium-config
        readinessProbe:
          httpGet: &id001
            path: /
            port: 8000
            httpHeaders:
            - name: Host
              value: localhost
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 15
        livenessProbe:
          httpGet: *id001
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 30
