name: CI/CD to Minikube
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
      - name: Build image inside Minikube
        run: |
          eval $(minikube docker-env)
          docker build -t lithium-app-latest:latest .
      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/lithium-app-latest